name: Docker
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: luxtorpeda-dev/build-number@28d7a55
      with:
        token: ${{ secrets.github_token }}
  push:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Steam Runtime
        run: git clone https://github.com/ValveSoftware/steam-runtime.git
      - name: Build image
        run: ./steam-runtime/setup_docker.sh --beta i386 --extra-bootstrap=luxtorpeda-bootstrap.sh runtime
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=luxtorpedadev/runtime-32
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=${{ needs.setup.outputs.build_number }}

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag runtime $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
